cable_data={
            "CU/PVC/PVC": {
                            "ground":[
                                {"size":1.5, "current": 21},
                                {"size":2.5, "current": 27},
                                {"size": 4, "current": 35},
                                {"size": 6, "current": 45},
                                {"size": 10, "current": 60},
                                {"size": 16, "current": 75},
                                {"size": 25, "current": 100},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 175},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 240},
                                {"size": 150, "current": 270},
                                {"size": 185, "current": 300},
                                {"size": 240, "current": 345},
                                {"size": 300, "current": 390},
                            ],
                            "duct":[
                                {"size":1.5, "current": 18},
                                {"size":2.5, "current": 23},
                                {"size": 4, "current": 30},
                                {"size": 6, "current": 36},
                                {"size": 10, "current": 48},
                                {"size": 16, "current": 60},
                                {"size": 25, "current": 80},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 115},
                                {"size": 70, "current": 145},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 195},
                                {"size": 150, "current": 220},
                                {"size": 185, "current": 245},
                                {"size": 240, "current": 290},
                                {"size": 300, "current": 320}
                            ],
                            "air":[
                                {"size":1.5, "current": 18},
                                {"size":2.5, "current": 22},
                                {"size": 4, "current": 31},
                                {"size": 6, "current": 39},
                                {"size": 10, "current": 53},
                                {"size": 16, "current": 72},
                                {"size": 25, "current": 94},
                                {"size": 35, "current": 110},
                                {"size": 50, "current": 138},
                                {"size": 70, "current": 171},
                                {"size": 95, "current": 209},
                                {"size": 120, "current": 242},
                                {"size": 150, "current": 275},
                                {"size": 185, "current": 314},
                                {"size": 240, "current": 374},
                                {"size": 300, "current": 440}
                            ]
                            },
            "AL/PVC/PVC": {
                            "ground":[
                                {"size": 10, "current": 42},
                                {"size": 16, "current": 53},
                                {"size": 25, "current": 70},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 115},
                                {"size": 70, "current": 135},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 185},
                                {"size": 150, "current": 210},
                                {"size": 185, "current": 235},
                                {"size": 240, "current": 275},
                                {"size": 300, "current": 310}
                            ],
                            "duct":[
                                {"size": 10, "current": 34},
                                {"size": 16, "current": 42},
                                {"size": 25, "current": 56},
                                {"size": 35, "current": 75},
                                {"size": 50, "current": 85},
                                {"size": 70, "current": 110},
                                {"size": 95, "current": 130},
                                {"size": 120, "current": 150},
                                {"size": 150, "current": 170},
                                {"size": 185, "current": 195},
                                {"size": 240, "current": 225},
                                {"size": 300, "current": 260}
                            ],
                            "air":[
                                {"size": 10, "current": 37},
                                {"size": 16, "current": 50},
                                {"size": 25, "current": 66},
                                {"size": 35, "current": 88},
                                {"size": 50, "current": 105},
                                {"size": 70, "current": 132},
                                {"size": 95, "current": 160},
                                {"size": 120, "current": 187},
                                {"size": 150, "current": 215},
                                {"size": 185, "current": 248},
                                {"size": 240, "current": 292},
                                {"size": 300, "current": 347}
                            ]
                            },
            "CU/PVC/STA/PVC": {
                            "ground":[
                                {"size": 4, "current": 35},
                                {"size": 6, "current": 45},
                                {"size": 10, "current": 60},
                                {"size": 16, "current": 75},
                                {"size": 25, "current": 100},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 175},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 240},
                                {"size": 150, "current": 270},
                                {"size": 185, "current": 300},
                                {"size": 240, "current": 345},
                                {"size": 300, "current": 390}
                            ],
                            "duct":[
                                {"size": 4, "current": 30},
                                {"size": 6, "current": 36},
                                {"size": 10, "current": 48},
                                {"size": 16, "current": 60},
                                {"size": 25, "current": 80},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 115},
                                {"size": 70, "current": 145},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 195},
                                {"size": 150, "current": 220},
                                {"size": 185, "current": 245},
                                {"size": 240, "current": 290},
                                {"size": 300, "current": 320}
                            ],
                            "air":[
                                {"size": 4, "current": 31},
                                {"size": 6, "current": 39},
                                {"size": 10, "current": 53},
                                {"size": 16, "current": 72},
                                {"size": 25, "current": 94},
                                {"size": 35, "current": 110},
                                {"size": 50, "current": 138},
                                {"size": 70, "current": 171},
                                {"size": 95, "current": 209},
                                {"size": 120, "current": 242},
                                {"size": 150, "current": 275},
                                {"size": 185, "current": 314},
                                {"size": 240, "current": 374},
                                {"size": 300, "current": 440}
                            ]
                            },
            "AL/PVC/STA/PVC": {
                            "ground":[
                                {"size": 10, "current": 42},
                                {"size": 16, "current": 53},
                                {"size": 25, "current": 70},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 115},
                                {"size": 70, "current": 135},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 185},
                                {"size": 150, "current": 210},
                                {"size": 185, "current": 235},
                                {"size": 240, "current": 275},
                                {"size": 300, "current": 310}
                            ],
                            "duct":[
                                {"size": 10, "current": 34},
                                {"size": 16, "current": 42},
                                {"size": 25, "current": 56},
                                {"size": 35, "current": 75},
                                {"size": 50, "current": 85},
                                {"size": 70, "current": 110},
                                {"size": 95, "current": 130},
                                {"size": 120, "current": 150},
                                {"size": 150, "current": 170},
                                {"size": 185, "current": 195},
                                {"size": 240, "current": 225},
                                {"size": 300, "current": 260}
                            ],
                            "air":[
                                {"size": 10, "current": 37},
                                {"size": 16, "current": 50},
                                {"size": 25, "current": 66},
                                {"size": 35, "current": 88},
                                {"size": 50, "current": 105},
                                {"size": 70, "current": 132},
                                {"size": 95, "current": 160},
                                {"size": 120, "current": 187},
                                {"size": 150, "current": 215},
                                {"size": 185, "current": 248},
                                {"size": 240, "current": 292},
                                {"size": 300, "current": 347}
                            ]
                            },
            "CU/PVC/SWA/PVC": {
                            "ground":[
                                {"size": 4, "current": 37},
                                {"size": 6, "current": 47},
                                {"size": 10, "current": 63},
                                {"size": 16, "current": 79},
                                {"size": 25, "current": 105},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 175},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 240},
                                {"size": 150, "current": 270},
                                {"size": 185, "current": 300},
                                {"size": 240, "current": 345},
                                {"size": 300, "current": 390}
                            ],
                            "duct":[
                                {"size": 4, "current": 29},
                                {"size": 6, "current": 37},
                                {"size": 10, "current": 50},
                                {"size": 16, "current": 68},
                                {"size": 25, "current": 89},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 115},
                                {"size": 70, "current": 145},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 195},
                                {"size": 150, "current": 220},
                                {"size": 185, "current": 245},
                                {"size": 240, "current": 290},
                                {"size": 300, "current": 320}
                            ],
                            "air":[
                                {"size":1.5, "current": 29},
                                {"size":2.5, "current": 37},
                                {"size": 4, "current": 50},
                                {"size": 6, "current": 68},
                                {"size": 10, "current": 89},
                                {"size": 16, "current": 116},
                                {"size": 25, "current": 143},
                                {"size": 35, "current": 176},
                                {"size": 50, "current": 138},
                                {"size": 70, "current": 171},
                                {"size": 95, "current": 215},
                                {"size": 120, "current": 248},
                                {"size": 150, "current": 281},
                                {"size": 185, "current": 319},
                                {"size": 240, "current": 380},
                                {"size": 300, "current": 446}
                            ]
                            },
            "AL/PVC/SWA/PVC": {
                            "ground":[
                                {"size": 10, "current": 42},
                                {"size": 16, "current": 53},
                                {"size": 25, "current": 70},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 115},
                                {"size": 70, "current": 135},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 185},
                                {"size": 150, "current": 210},
                                {"size": 185, "current": 235},
                                {"size": 240, "current": 275},
                                {"size": 300, "current": 310}
                            ],
                            "duct":[
                                {"size": 10, "current": 34},
                                {"size": 16, "current": 42},
                                {"size": 25, "current": 56},
                                {"size": 35, "current": 75},
                                {"size": 50, "current": 85},
                                {"size": 70, "current": 110},
                                {"size": 95, "current": 130},
                                {"size": 120, "current": 150},
                                {"size": 150, "current": 170},
                                {"size": 185, "current": 195},
                                {"size": 240, "current": 225},
                                {"size": 300, "current": 260}
                            ],
                            "air":[
                                {"size": 10, "current": 37},
                                {"size": 16, "current": 50},
                                {"size": 25, "current": 66},
                                {"size": 35, "current": 88},
                                {"size": 50, "current": 105},
                                {"size": 70, "current": 138},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 193},
                                {"size": 150, "current": 220},
                                {"size": 185, "current": 253},
                                {"size": 240, "current": 297},
                                {"size": 300, "current": 352}
                            ]
                            },
            "CU/XLPE/PVC": {
                            "ground":[
                                {"size":1.5, "current": 26},
                                {"size":2.5, "current": 35},
                                {"size": 4, "current": 45},
                                {"size": 6, "current": 57},
                                {"size": 10, "current": 75},
                                {"size": 16, "current": 97},
                                {"size": 25, "current": 128},
                                {"size": 35, "current": 155},
                                {"size": 50, "current": 185},
                                {"size": 70, "current": 220},
                                {"size": 95, "current": 265},
                                {"size": 120, "current": 305},
                                {"size": 150, "current": 335},
                                {"size": 185, "current": 375},
                                {"size": 240, "current": 435},
                                {"size": 300, "current": 490}
                            ],
                            "duct":[
                                {"size":1.5, "current": 23},
                                {"size":2.5, "current": 29},
                                {"size": 4, "current": 36},
                                {"size": 6, "current": 45},
                                {"size": 10, "current": 60},
                                {"size": 16, "current": 75},
                                {"size": 25, "current": 102},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 180},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 245},
                                {"size": 150, "current": 275},
                                {"size": 185, "current": 310},
                                {"size": 240, "current": 365},
                                {"size": 300, "current": 405}
                            ],
                            "air":[
                                {"size":1.5, "current": 22},
                                {"size":2.5, "current": 32},
                                {"size": 4, "current": 41},
                                {"size": 6, "current": 50},
                                {"size": 10, "current": 68},
                                {"size": 16, "current": 89},
                                {"size": 25, "current": 120},
                                {"size": 35, "current": 145},
                                {"size": 50, "current": 179},
                                {"size": 70, "current": 225},
                                {"size": 95, "current": 268},
                                {"size": 120, "current": 310},
                                {"size": 150, "current": 352},
                                {"size": 185, "current": 404},
                                {"size": 240, "current": 483},
                                {"size": 300, "current": 562}
                            ]
                            },
            "AL/XLPE/PVC": {
                            "ground":[
                                {"size": 10, "current": 52},
                                {"size": 16, "current": 68},
                                {"size": 25, "current": 90},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 175},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 235},
                                {"size": 150, "current": 265},
                                {"size": 185, "current": 290},
                                {"size": 240, "current": 340},
                                {"size": 300, "current": 390}
                            ],
                            "duct":[
                                {"size": 10, "current": 42},
                                {"size": 16, "current": 52},
                                {"size": 25, "current": 71},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 110},
                                {"size": 70, "current": 140},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 190},
                                {"size": 150, "current": 215},
                                {"size": 185, "current": 240},
                                {"size": 240, "current": 280},
                                {"size": 300, "current": 315}
                            ],
                            "air":[
                                {"size": 10, "current": 48},
                                {"size": 16, "current": 62},
                                {"size": 25, "current": 84},
                                {"size": 35, "current": 110},
                                {"size": 50, "current": 136},
                                {"size": 70, "current": 168},
                                {"size": 95, "current": 205},
                                {"size": 120, "current": 236},
                                {"size": 150, "current": 278},
                                {"size": 185, "current": 315},
                                {"size": 240, "current": 378},
                                {"size": 300, "current": 446}
                            ]
                            },
            "CU/XLPE/STA/PVC": {
                            "ground":[
                                {"size": 6, "current": 56},
                                {"size": 10, "current": 74},
                                {"size": 16, "current": 96},
                                {"size": 25, "current": 127},
                                {"size": 35, "current": 153},
                                {"size": 50, "current": 185},
                                {"size": 70, "current": 220},
                                {"size": 95, "current": 265},
                                {"size": 120, "current": 305},
                                {"size": 150, "current": 335},
                                {"size": 185, "current": 375},
                                {"size": 240, "current": 435},
                                {"size": 300, "current": 490}
                            ],
                            "duct":[
                                {"size": 6, "current": 44},
                                {"size": 10, "current": 59},
                                {"size": 16, "current": 74},
                                {"size": 25, "current": 100},
                                {"size": 35, "current": 119},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 180},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 245},
                                {"size": 150, "current": 275},
                                {"size": 185, "current": 310},
                                {"size": 240, "current": 365},
                                {"size": 300, "current": 405}
                            ],
                            "air":[
                                {"size": 6, "current": 49},
                                {"size": 10, "current": 67},
                                {"size": 16, "current": 88},
                                {"size": 25, "current": 120},
                                {"size": 35, "current": 143},
                                {"size": 50, "current": 178},
                                {"size": 70, "current": 215},
                                {"size": 95, "current": 268},
                                {"size": 120, "current": 310},
                                {"size": 150, "current": 352},
                                {"size": 185, "current": 404},
                                {"size": 240, "current": 483},
                                {"size": 300, "current": 562}
                            ]
                            },
            "AL/XLPE/STA/PVC": {
                            "ground":[
                                {"size": 10, "current": 52},
                                {"size": 16, "current": 67},
                                {"size": 25, "current": 89},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 175},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 235},
                                {"size": 150, "current": 265},
                                {"size": 185, "current": 290},
                                {"size": 240, "current": 340},
                                {"size": 300, "current": 390}
                            ],
                            "duct":[
                                {"size": 10, "current": 41},
                                {"size": 16, "current": 52},
                                {"size": 25, "current": 70},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 110},
                                {"size": 70, "current": 140},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 190},
                                {"size": 150, "current": 215},
                                {"size": 185, "current": 240},
                                {"size": 240, "current": 280},
                                {"size": 300, "current": 315}
                            ],
                            "air":[
                                {"size": 10, "current": 47},
                                {"size": 16, "current": 62},
                                {"size": 25, "current": 84},
                                {"size": 35, "current": 110},
                                {"size": 50, "current": 136},
                                {"size": 70, "current": 168},
                                {"size": 95, "current": 205},
                                {"size": 120, "current": 236},
                                {"size": 150, "current": 278},
                                {"size": 185, "current": 315},
                                {"size": 240, "current": 378},
                                {"size": 300, "current": 446}
                            ]
                            },
            "CU/XLPE/SWA/PVC": {
                            "ground":[
                                {"size": 4, "current": 46},
                                {"size": 6, "current": 58},
                                {"size": 10, "current": 76},
                                {"size": 16, "current": 98},
                                {"size": 25, "current": 130},
                                {"size": 35, "current": 158},
                                {"size": 50, "current": 185},
                                {"size": 70, "current": 220},
                                {"size": 95, "current": 265},
                                {"size": 120, "current": 305},
                                {"size": 150, "current": 335},
                                {"size": 185, "current": 375},
                                {"size": 240, "current": 435},
                                {"size": 300, "current": 490}
                            ],
                            "duct":[
                                {"size": 4, "current": 37},
                                {"size": 6, "current": 46},
                                {"size": 10, "current": 61},
                                {"size": 16, "current": 76},
                                {"size": 25, "current": 103},
                                {"size": 35, "current": 122},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 180},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 245},
                                {"size": 150, "current": 275},
                                {"size": 185, "current": 310},
                                {"size": 240, "current": 365},
                                {"size": 300, "current": 405}
                            ],
                            "air":[
                                {"size": 4, "current": 42},
                                {"size": 6, "current": 51},
                                {"size": 10, "current": 69},
                                {"size": 16, "current": 90},
                                {"size": 25, "current": 122},
                                {"size": 35, "current": 147},
                                {"size": 50, "current": 184},
                                {"size": 70, "current": 220},
                                {"size": 95, "current": 273},
                                {"size": 120, "current": 315},
                                {"size": 150, "current": 375},
                                {"size": 185, "current": 410},
                                {"size": 240, "current": 488},
                                {"size": 300, "current": 562}
                            ]
                            },
            "AL/XLPE/SWA/PVC": {
                            "ground":[
                                {"size": 10, "current": 52},
                                {"size": 16, "current": 67},
                                {"size": 25, "current": 89},
                                {"size": 35, "current": 120},
                                {"size": 50, "current": 145},
                                {"size": 70, "current": 175},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 235},
                                {"size": 150, "current": 265},
                                {"size": 185, "current": 290},
                                {"size": 240, "current": 340},
                                {"size": 300, "current": 390}
                            ],
                            "duct":[
                                {"size": 10, "current": 41},
                                {"size": 16, "current": 52},
                                {"size": 25, "current": 70},
                                {"size": 35, "current": 95},
                                {"size": 50, "current": 110},
                                {"size": 70, "current": 140},
                                {"size": 95, "current": 165},
                                {"size": 120, "current": 190},
                                {"size": 150, "current": 215},
                                {"size": 185, "current": 240},
                                {"size": 240, "current": 280},
                                {"size": 300, "current": 315}
                            ],
                            "air":[
                                {"size": 10, "current": 52},
                                {"size": 16, "current": 67},
                                {"size": 25, "current": 89},
                                {"size": 35, "current": 115},
                                {"size": 50, "current": 141},
                                {"size": 70, "current": 173},
                                {"size": 95, "current": 210},
                                {"size": 120, "current": 241},
                                {"size": 150, "current": 283},
                                {"size": 185, "current": 320},
                                {"size": 240, "current": 383},
                                {"size": 300, "current": 451}
                            ]
                            },
}
